include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/*
    - lib/**/*.g.dart
    - lib/**/*.config.dart

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: true
    implicit_call_tearoffs: false
