version: "3.8"
volumes:
  pg_data:

services:
  api:
    image: wooglife-api
    build:
      context: .
    environment:
      POSTGRES_HOSTNAME: db
    ports:
    - 8080:8080
  db:
    volumes:
      - pg_data:/data
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: pw
    ports:
      - 5432:5432
