version: "3.8"
volumes:
  data:
  pg_data:

services:
  api:
    volumes:
      - data:/data
    image: wooglife-api
    build:
      context: .
  db:
    volumes:
      - pg_data:/data
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: pw
    ports:
      - 5432:5432
