name: woog_api
description: The REST API for the Woog temperature.
version: 0.3.0
homepage: https://github.com/woog-life/api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Static analysis
  meta: ^1.3.0

  # Logging
  logger: ^1.0.0

  # Dependency injection
  get_it: ^7.0.0
  injectable: ^1.0.0

  # Web server
  shelf: ^1.1.0

  # Routing
  shelf_router: ^1.0.0

  # JSON serialization
  json_annotation: ^4.0.0


dev_dependencies:
  test: ^1.14.4
  lint: ^1.5.0

  build_runner: ^2.0.0

  json_serializable: ^4.1.0

  injectable_generator: ^1.0.0

  # Access to info from pubspec
  build_version: ^2.0.0

  shelf_router_generator: ^1.0.0
