name: woog_api
description: The REST API for the Woog temperature.
version: 0.14.0
homepage: https://github.com/woog-life/api

environment:
  sdk: '^3.0.0'

dependencies:
  country_code: ^1.0.0

  # Dependency injection
  get_it: ^7.0.0
  injectable: ^2.0.0

  # JSON serialization
  json_annotation: 4.8.1

  # Logging
  logger: ^2.0.0

  # Static analysis
  meta: ^1.0.0

  # Database
  postgres: ^3.0.0

  # That juicy UUID stuff
  sane_uuid: 1.0.0-alpha.5

  # Alerting
  sentry: ^7.0.0

  # Web server
  shelf: ^1.0.0

  # Routingdrop
  shelf_router: ^1.0.0

  # Static file serving
  shelf_static: ^1.0.0

  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0
  injectable_generator: ^2.0.0
  json_serializable: 6.7.1
  lints: ^3.0.0
  shelf_router_generator: ^1.0.0
  test: ^1.0.0
