name: woog_api
description: The REST API for the Woog temperature.
version: 0.14.0
homepage: https://github.com/woog-life/api

environment:
  sdk: '^3.0.0'

dependencies:
  country_code: ^1.0.0
  get_it: ^7.0.0
  injectable: ^2.0.0
  json_annotation: 4.8.1
  logger: ^2.0.0
  meta: ^1.0.0
  postgres: ^3.0.0
  sane_uuid: 1.0.0-alpha.5
  sentry: ^7.0.0
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0
  injectable_generator: ^2.0.0
  json_serializable: 6.7.1
  lints: ^3.0.0
  shelf_router_generator: ^1.0.0
  test: ^1.0.0
