name: woog_api
description: The REST API for the Woog temperature.
version: 0.12.0
homepage: https://github.com/woog-life/api

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # Dependency injection
  get_it: ^7.0.0
  injectable: ^1.0.0

  # JSON serialization
  json_annotation: ^4.0.0

  # Logging
  logger: ^1.0.0

  # Static analysis
  meta: ^1.0.0

  # Database
  postgres: ^2.0.0

  # That juicy UUID stuff
  sane_uuid: ^1.0.0-alpha.3

  # Alerting
  sentry: ^5.0.0

  # Web server
  shelf: ^1.0.0

  # Routing
  shelf_router: ^1.0.0

  # Static file serving
  shelf_static: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0
  injectable_generator: ^1.0.0
  json_serializable: ^4.0.0
  lints: ^1.0.0
  shelf_router_generator: ^1.0.0
  test: ^1.0.0
