name: woog_api
description: The REST API for the Woog temperature.
version: 0.1.0-alpha.1
homepage: https://github.com/woog-life/api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Static analysis
  meta: ^1.3.0

  # Web server
  shelf: ^1.1.0

  # Routing
  shelf_router: ^1.0.0


dev_dependencies:
  test: ^1.14.4
  lint: ^1.5.0

  build_runner: ^1.12.2
