---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/woog-life/api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 2m
              memory: 32Mi
            limits:
              cpu: 20m
              memory: 64Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - configMapRef:
                name: backend-postgres-config
            - secretRef:
                name: woog-secrets
