apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  OTEL_EXPORTER_CONSOLE: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.openTelemetry.endpoint }}"
  POSTGRES_DB: "{{ .Values.postgres.db }}"
  POSTGRES_HOSTNAME: "{{ .Values.postgres.host }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_USE_TLS: "true"
