apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_HOSTNAME: {{ .Values.postgres.host }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
