---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wooglife
  name: backend
  labels:
    app: backend
spec:
  revisionHistoryLimit: 1
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.api.image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 25m
              memory: 64Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - configMapRef:
                name: backend-postgres-config
            - secretRef:
                name: woog-secrets
