---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.api.image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 2m
              memory: 32Mi
            limits:
              cpu: 20m
              memory: 64Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - configMapRef:
                name: backend-postgres-config
            - secretRef:
                name: woog-secrets
