---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-postgres-config
data:
  POSTGRES_DB: woog
  POSTGRES_HOSTNAME: backend-postgres
  POSTGRES_USER: woog
  PGDATA: /pg/13/data
---
apiVersion: v1
kind: Service
metadata:
  name: backend-postgres
spec:
  ports:
    - name: psql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: backend-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-postgres
  labels:
    app: backend-postgres
spec:
  replicas: 1
  serviceName: backend-postgres
  revisionHistoryLimit: 1
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: backend-postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  selector:
    matchLabels:
      app: backend-postgres
  template:
    metadata:
      labels:
        app: backend-postgres
    spec:
      volumes:
        - name: olddata
          persistentVolumeClaim:
            claimName: backend-postgres-data
      containers:
        - name: backend-postgres
          image: postgres:13-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /pg
              name: backend-postgres
          envFrom:
            - secretRef:
                name: woog-secrets
            - configMapRef:
                name: backend-postgres-config
