name: Workflow
on:
  push:
    branches:
      - 'main'
  pull_request:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: dart:2.19
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run tests
        run: dart test

  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    container: dart:2.19
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Check bin formatting
        run: dart format bin --set-exit-if-changed
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed
      - name: Check test formatting
        run: dart format test --set-exit-if-changed

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: dart:2.19
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run Analysis
        run: dart analyze --fatal-infos

  build_docker:
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'pull_request'
    needs:
      - check_format
      - lint
      - test
    steps:
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          build_args: |
            build=citest
          tags: ghcr.io/${{ github.repository }}/app:${{ github.sha }}

  push_migrations_docker:
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    needs:
      - check_format
      - lint
      - test
    steps:
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: migrations
          push: true
          tags: ghcr.io/${{ github.repository }}/migrations:${{ github.sha }}

  push_docker:
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    needs:
      - check_format
      - lint
      - test
    steps:
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          build_args: |
            build=${{ github.sha }}
          push: true
          tags: ghcr.io/${{ github.repository }}/app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [push_docker, push_migrations_docker]
    steps:
      - uses: actions/checkout@v3
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade backend . --install --namespace=wooglife --atomic
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'
